apiVersion: v1
kind: Pod
metadata:
  name: ns-multi-pod
  namespace: demo-ns
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports:
    - containerPort: 80

  - name: busybox-container
    image: busybox
    command: ["sh", "-c", "while true; do echo Running in namespace demo-ns; sleep 10; done"]

